tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary": "#F97306",
              "on-secondary-fixed": "#281900",
              "surface-container-low": "#fff1eb",
              "secondary-fixed-dim": "#fdbb3f",
              "muted": "#EDE6DC",
              "muted-foreground": "#7A7068",
              "outline": "#8c7164",
              "inverse-primary": "#ffb68e",
              "tertiary": "#00629d",
              "background": "#FAF7F1",
              "tertiary-fixed": "#cfe5ff",
              "accent-red": "#DF2020",
              "surface-container": "#ffeae0",
              "surface-dim": "#edd5ca",
              "on-primary-container": "#562300",
              "outline-variant": "#e0c0b0",
              "primary-fixed-dim": "#ffb68e",
              "error-container": "#ffdad6",
              "secondary-fixed": "#ffdeac",
              "on-tertiary": "#ffffff",
              "on-error": "#ffffff",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#331200",
              "on-primary-fixed-variant": "#773300",
              "destructive": "#EF4444",
              "surface-bright": "#fff8f6",
              "error": "#ba1a1a",
              "on-secondary-fixed-variant": "#604100",
              "border": "#E3DBD0",
              "surface": "#fff8f6",
              "tertiary-container": "#00a1fd",
              "surface-variant": "#f6ded2",
              "on-tertiary-container": "#003558",
              "surface-container-highest": "#f6ded2",
              "dark-background": "#1F1812",
              "on-tertiary-fixed-variant": "#004a78",
              "on-tertiary-fixed": "#001d34",
              "on-surface": "#251912",
              "card": "#FDFBF7",
              "on-surface-variant": "#584236",
              "surface-container-lowest": "#ffffff",
              "on-error-container": "#93000a",
              "dark-card": "#2A221C",
              "on-background": "#251912",
              "inverse-on-surface": "#ffede5",
              "secondary": "#7e5700",
              "tertiary-fixed-dim": "#99cbff",
              "warm-tint": "#FBF1E6",
              "primary-container": "#f97306",
              "foreground": "#26201A",
              "surface-tint": "#F97306",
              "secondary-container": "#fdbb3f",
              "primary-fixed": "#ffdbca",
              "on-secondary-container": "#6f4c00",
              "inverse-surface": "#3c2d26",
              "on-secondary": "#ffffff",
              "golden": "#F8C123",
              "surface-container-high": "#fce3d8"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px",
              "2xl": "1.5rem"
      },
      "spacing": {
              "hero-gap": "2.5rem",
              "nav-height": "4rem",
              "section-py-desktop": "6rem",
              "gutter-grid": "1.5rem",
              "section-py-mobile": "4rem",
              "container-max": "1400px"
      },
      "fontFamily": {
              "body-default": ["DM Sans", "sans-serif"],
              "pill-badge": ["DM Sans", "sans-serif"],
              "h3-card": ["Playfair Display", "serif"],
              "h1-hero": ["Playfair Display", "serif"],
              "body-lead": ["DM Sans", "sans-serif"],
              "h2-section": ["Playfair Display", "serif"],
              "nav-link": ["DM Sans", "sans-serif"]
      },
      "fontSize": {
              "body-default": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "pill-badge": ["14px", {"lineHeight": "1", "fontWeight": "600"}],
              "h3-card": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
              "h1-hero": ["48px", {"lineHeight": "1.1", "fontWeight": "900"}],
              "body-lead": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "h2-section": ["30px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "nav-link": ["14px", {"lineHeight": "1", "fontWeight": "500"}]
      }
    },
  },
}